monolog:
    channels:
        - pipeline
    handlers:
        pipeline:
            type: stream
            channels: [pipeline]
            path: "%kernel.logs_dir%/%kernel.environment%_bout_de_code_sylius_etl_plugin.log"
